name: stable

on:
  push:
    branches: [ main ]
    paths:
      - '*/Dockerfile'
      - '.github/workflows/stable.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*/Dockerfile'
      - '.github/workflows/stable.yml'
  schedule:
    - cron: '0 10 2 * *'
  workflow_dispatch:

env:
  VERSION_RE: v3.8.0
  VERSION_BARESIP: v3.8.0

jobs:
  libre:
    env:
        IMAGE_NAME: ${{ github.repository }}/libre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Build
    #   run: |
    #     docker build libre -t libre \
    #         --build-arg VERSION=${{ env.VERSION_RE }} \

    - name: Buildx, Tag and Push image
      # if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: libre
        platforms: linux/amd64,linux/arm64
        push: github.event_name != 'pull_request'
        build-args: VERSION=${{ env.VERSION_RE }}
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_RE }}
          ghcr.io/${{ env.IMAGE_NAME }}:latest

      # run: |

      #   docker tag libre ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_RE }}
      #   docker tag libre ghcr.io/${{ env.IMAGE_NAME }}:latest
      #   docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_RE }}
      #   docker push ghcr.io/${{ env.IMAGE_NAME }}:latest

  baresip:
    env:
        IMAGE_NAME: ${{ github.repository }}/baresip
    needs: [ "libre" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build, Tag and Push Image
      # run: |
      #   docker build baresip -t baresip \
      #     --build-arg VERSION=${{ env.VERSION_BARESIP }} \
      #     --build-arg IMAGE=ghcr.io/baresip/docker/libre:latest \
      uses: docker/build-push-action@v5
      with:
        context: baresip
        platforms: linux/amd64,linux/arm64
        push: github.event_name != 'pull_request'
        build-args: |
          VERSION=${{ env.VERSION_BARESIP }}
          IMAGE=ghcr.io/baresip/docker/libre:latest
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_BARESIP }}
          ghcr.io/${{ env.IMAGE_NAME }}:latest
    # - name: Tag and Push image
    #   if: github.event_name != 'pull_request'
    #   run: |
    #     docker tag baresip ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_BARESIP }}
    #     docker tag baresip ghcr.io/${{ env.IMAGE_NAME }}:latest
    #     docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_BARESIP }}
    #     docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
