name: stable

on:
  push:
    branches: [ main ]
    paths:
      - '*/Dockerfile'
      - '.github/workflows/stable.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*/Dockerfile'
      - '.github/workflows/stable.yml'
  schedule:
    - cron: '0 10 2 * *'
  workflow_dispatch:

env:
  VERSION_RE: v3.8.0
  VERSION_BARESIP: v3.8.0

jobs:
  libre:
    timeout-minutes: 90
    env:
        IMAGE_NAME: ${{ github.repository }}/libre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Buildx, Tag and Push image
      uses: docker/build-push-action@v5
      with:
        context: libre
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        build-args: VERSION=${{ env.VERSION_RE }}
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_RE }}
          ghcr.io/${{ env.IMAGE_NAME }}:latest
  baresip:
    timeout-minutes: 90
    env:
        IMAGE_NAME: ${{ github.repository }}/baresip
    needs: [ "libre" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build, Tag and Push Image
      uses: docker/build-push-action@v5
      with:
        context: baresip
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        build-args: |
          VERSION=${{ env.VERSION_BARESIP }}
          IMAGE=ghcr.io/baresip/docker/libre:latest
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_BARESIP }}
          ghcr.io/${{ env.IMAGE_NAME }}:latest
